/**
 * * Auth Types
 */
const AUTH = {
  SAVE_TOKEN_USER: "SAVE_TOKEN_USER",
  CLEAR_FORM_LOGIN: "CLEAR_FORM_LOGIN",
  LOGOUT: "LOGOUT",
};

/**
 * * Drawer Types
 */
const DRAWER = {};

/**
 * * Proyect Types
 */
const PROYECT = {
  SET_PROYECTS: "SET_PROYECTS",
  SET_PROYECT: "SET_PROYECT",
  SET_FORM: "SET_FORM",
  ADD_PROYECT: "ADD_PROYECT",
  TOGGLE_FORM: "TOGGLE_FORM",
  TOGGLE_DELETE_DIALOG: "TOGGLE_DELETE_DIALOG",
  REMOVE_PROYECT: "REMOVE_PROYECT",
};

const USER = {
  SET_USERS: "SET_USERS",
};

const TASK = {
  SET_TASKS: "SET_TASKS",
  SET_TASK: "SET_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  SET_SUBTASK: "SET_SUBTASK",
  SHOW_EDIT_SUBTASK_DIALOG: "SHOW_EDIT_SUBTASK_DIALOG",
};

export { AUTH, DRAWER, PROYECT, USER, TASK };
