/**
 * * Auth Types
 */
const AUTH = {
  SAVE_TOKEN_USER: "SAVE_TOKEN_USER",
  CLEAR_FORM_LOGIN: "CLEAR_FORM_LOGIN",
  LOGOUT: "LOGOUT",
};

/**
 * * Drawer Types
 */
const DRAWER = {};

/**
 * * Proyect Types
 */
const PROYECT = {
  SET_PROYECTS: "SET_PROYECTS",
  SET_PROYECT: "SET_PROYECT",
  ADD_PROYECT: "ADD_PROYECT",
  TOGGLE_FORM: "TOGGLE_FORM",
  TOGGLE_DELETE_DIALOG: "TOGGLE_DELETE_DIALOG",
  REMOVE_PROYECT: "REMOVE_PROYECT",
};

export { AUTH, DRAWER, PROYECT };
